---
pool: Default

trigger: none
pr:
  - main
steps:
    - task: Maven@4
      inputs:
        mavenPOMFile: 'pom.xml' 
        goals: package
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        ##jdkVersionOption: '1.17'
    - task: CopyFiles@2
      inputs:
        Contents: '**/spring-petclinic*.jar/'
        TargetFolder: $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: $(Build.ArtifactStagingDirectory)
        artifactName: $(Build.Repository.name)


